use serde_json::{json, Value};
use std::cell::RefCell;
use std::collections::HashMap;

const PRIMARY_THREAD: &str = "demo-thread-web-ui";
const SECONDARY_THREAD: &str = "demo-thread-protocol";
const PROJECT_PATH: &str = "/Users/demo/projects/codex-bridge";

thread_local! {
    static STATE: RefCell<DemoState> = RefCell::new(DemoState::new());
}

#[derive(Clone)]
struct PendingMessage {
    id: String,
    thread_id: String,
    text: String,
    action: String,
    status: String,
    polls: u8,
}

struct DemoState {
    messages: Vec<Value>,
    pending: Option<PendingMessage>,
    active_thread: Option<String>,
    active_ticks: u8,
    next_pending: u32,
    file_len: u64,
    model: String,
    effort: String,
    pinned_thread: Option<String>,
    renamed_threads: HashMap<String, String>,
}

impl DemoState {
    fn new() -> Self {
        Self {
            messages: seed_messages(),
            pending: None,
            active_thread: None,
            active_ticks: 0,
            next_pending: 1,
            file_len: 48_320,
            model: "gpt-5.6-sol".to_owned(),
            effort: "medium".to_owned(),
            pinned_thread: Some(PRIMARY_THREAD.to_owned()),
            renamed_threads: HashMap::new(),
        }
    }

    fn thread(&self, id: &str) -> Value {
        let (default_title, created_at) = if id == SECONDARY_THREAD {
            ("Typed app-server tool items", "2026-09-06T09:38:46.147Z")
        } else {
            (
                "Build an interactive Pages demo",
                "2026-09-07T06:30:15.726Z",
            )
        };
        let title = self
            .renamed_threads
            .get(id)
            .map(String::as_str)
            .unwrap_or(default_title);
        json!({
            "id": id,
            "title": title,
            "cwd": PROJECT_PATH,
            "git_branch": "main",
            "created_at": created_at,
            "updated_at_ms": 1_788_767_541_844_u64,
            "source": "demo",
            "archived": false,
            "pinned": self.pinned_thread.as_deref() == Some(id),
        })
    }

    fn append_user_message(&mut self, text: String) {
        self.messages.push(json!({
            "timestamp": "2026-09-07T07:00:00.000Z",
            "id": format!("demo-user-{}", self.messages.len()),
            "role": "user",
            "phase": null,
            "category": "user",
            "content": [{"kind": "text", "text": text}],
            "tools": [],
        }));
    }

    fn append_demo_reply(&mut self) {
        self.messages.push(json!({
            "timestamp": "2026-09-07T07:00:04.000Z",
            "id": format!("demo-assistant-{}", self.messages.len()),
            "role": "assistant",
            "phase": "final_answer",
            "category": "assistant",
            "content": [{
                "kind": "text",
                "text": "This reply was generated by the in-browser WASM demo server. No message left this page, but the queue, handoff, processing, and history-refresh flow is the same UI used by codex-bridge."
            }],
            "tools": [],
        }));
    }

    fn pending_messages(&mut self) -> Value {
        let visible = self.pending.as_ref().map(|pending| {
            json!({
                "id": pending.id,
                "thread_id": pending.thread_id,
                "text": pending.text,
                "action": pending.action,
                "status": pending.status,
                "source": "demo_wasm",
            })
        });

        if let Some(pending) = self.pending.as_mut() {
            pending.polls += 1;
            if pending.polls == 1 {
                pending.status = if pending.action == "steer" {
                    "steered".to_owned()
                } else {
                    "queued".to_owned()
                };
            }
        }

        let should_land = self
            .pending
            .as_ref()
            .is_some_and(|pending| pending.polls >= 3);
        if should_land {
            let pending = self.pending.take().expect("pending message exists");
            self.append_user_message(pending.text);
            self.active_thread = Some(pending.thread_id);
            self.active_ticks = 3;
            self.file_len += 1;
            return json!({"messages": []});
        }

        json!({"messages": visible.into_iter().collect::<Vec<_>>()})
    }

    fn activity(&mut self, thread_id: &str) -> Value {
        let active_here = self.active_thread.as_deref() == Some(thread_id) && self.active_ticks > 0;
        if active_here {
            self.active_ticks -= 1;
            if self.active_ticks == 0 {
                self.append_demo_reply();
                self.active_thread = None;
                self.file_len += 1;
            }
        }
        let still_active =
            self.active_thread.as_deref() == Some(thread_id) && self.active_ticks > 0;
        json!({
            "thread_id": thread_id,
            "activity": {
                "active_turn_id": still_active.then_some("demo-turn-processing"),
                "phase": still_active.then_some("model"),
                "active_tool": Value::Null,
                "file_len": self.file_len,
                "updated_at_ms": 1_788_767_541_844_u64 + self.file_len,
            }
        })
    }
}

fn seed_messages() -> Vec<Value> {
    vec![
        json!({
            "timestamp": "2026-09-07T06:30:15.726Z",
            "id": "demo-user-0",
            "role": "user",
            "phase": null,
            "category": "user",
            "content": [{"kind": "text", "text": "Build a GitHub Pages demo using the same responsive Web UI."}],
            "tools": [],
        }),
        json!({
            "timestamp": "2026-09-07T06:30:21.000Z",
            "id": "demo-assistant-1",
            "role": "assistant",
            "phase": "commentary",
            "category": "assistant",
            "content": [{"kind": "text", "text": "I’ll keep the production frontend intact and replace only its command transport with a small in-browser demo server."}],
            "tools": [{
                "tool_index": 0,
                "name": "exec_command",
                "status": "completed",
                "preview": "cargo build --target wasm32-unknown-unknown",
                "has_output": true,
                "bytes": 284,
                "additions": null,
                "deletions": null,
                "file_count": null
            }],
        }),
        json!({
            "timestamp": "2026-09-07T06:31:04.000Z",
            "id": "demo-assistant-2",
            "role": "assistant",
            "phase": "commentary",
            "category": "assistant",
            "content": [{"kind": "text", "text": "The demo server now speaks the bridge request protocol and returns typed tool details."}],
            "tools": [{
                "tool_index": 0,
                "name": "apply_patch",
                "status": "completed",
                "preview": "已编辑 3 个文件",
                "has_output": true,
                "bytes": 1240,
                "additions": 86,
                "deletions": 4,
                "file_count": 3
            }],
        }),
        json!({
            "timestamp": "2026-09-07T06:31:40.000Z",
            "id": "demo-user-3",
            "role": "user",
            "phase": null,
            "category": "user",
            "content": [{"kind": "text", "text": "Can visitors try submitting a message without connecting to my Mac?"}],
            "tools": [],
        }),
        json!({
            "timestamp": "2026-09-07T06:31:46.000Z",
            "id": "demo-assistant-4",
            "role": "assistant",
            "phase": "final_answer",
            "category": "assistant",
            "content": [{"kind": "text", "text": "Yes. Try the composer below: the WASM state machine demonstrates submission, queue handoff, processing, and a simulated response entirely inside your browser."}],
            "tools": [{
                "tool_index": 0,
                "name": "web_search",
                "status": "completed",
                "preview": "GitHub Pages WebAssembly MIME type",
                "has_output": true,
                "bytes": 376,
                "additions": null,
                "deletions": null,
                "file_count": null
            }],
        }),
    ]
}

fn models() -> Value {
    json!({"models": [
        {
            "id": "gpt-5.6-sol",
            "name": "GPT-5.6-Sol (demo)",
            "description": "A simulated model option for the Pages demo.",
            "default_effort": "medium",
            "efforts": [
                {"id": "low", "description": "Fast responses with lighter reasoning"},
                {"id": "medium", "description": "Balanced speed and reasoning depth"},
                {"id": "high", "description": "Greater reasoning depth"}
            ]
        },
        {
            "id": "gpt-5.4-mini",
            "name": "GPT-5.4-Mini (demo)",
            "description": "A compact simulated model option.",
            "default_effort": "low",
            "efforts": [
                {"id": "low", "description": "Fast demo responses"},
                {"id": "medium", "description": "More simulated reasoning"}
            ]
        }
    ]})
}

fn tool_content(message_index: usize, tool_index: usize) -> Option<Value> {
    match (message_index, tool_index) {
        (1, 0) => Some(json!({
            "display_input": {"type": "commandExecution", "command": "cargo build --release --target wasm32-unknown-unknown -p codex-bridge-demo", "cwd": PROJECT_PATH},
            "tool": {"call_id": "demo-command", "name": "exec_command", "status": "completed", "input": {"type": "commandExecution", "command": "cargo build --release --target wasm32-unknown-unknown -p codex-bridge-demo", "cwd": PROJECT_PATH}, "output": {"exitCode": 0, "aggregatedOutput": "Finished release profile [optimized]"}}
        })),
        (2, 0) => Some(json!({
            "display_input": {"type": "fileChange", "changes": [
                {"path": format!("{PROJECT_PATH}/crates/codex-bridge-demo/src/lib.rs"), "kind": {"type": "add", "move_path": null}, "diff": "@@ -0,0 +1,5 @@\n+pub fn demo_command(request: &str) -> String {\n+    dispatch(request)\n+}\n"},
                {"path": format!("{PROJECT_PATH}/web-ui/src/api.js"), "kind": {"type": "update", "move_path": null}, "diff": "@@ -1,3 +1,5 @@\n+const demoMode = import.meta.env.VITE_CODEX_BRIDGE_DEMO === \\\"1\\\";\n export async function command(request) {\n"},
                {"path": format!("{PROJECT_PATH}/.github/workflows/pages.yml"), "kind": {"type": "update", "move_path": null}, "diff": "@@ -20,2 +20,4 @@\n+      - run: cargo build --target wasm32-unknown-unknown\n+      - run: npm run build\n"}
            ]},
            "tool": {"call_id": "demo-patch", "name": "apply_patch", "status": "completed", "input": {"type": "fileChange"}, "output": {"success": true}}
        })),
        (4, 0) => Some(json!({
            "display_input": {"type": "webSearch", "query": "GitHub Pages WebAssembly MIME type"},
            "tool": {"call_id": "demo-search", "name": "web_search", "status": "completed", "input": {"type": "webSearch", "query": "GitHub Pages WebAssembly MIME type"}, "output": {"result": "GitHub Pages serves .wasm assets for browser instantiation."}}
        })),
        _ => None,
    }
}

fn success(result: Value) -> Value {
    json!({"ok": true, "result": result})
}

fn error(code: &str, message: impl Into<String>) -> Value {
    json!({"ok": false, "error": {"code": code, "message": message.into()}})
}

fn dispatch(request: Value, state: &mut DemoState) -> Value {
    let Some(command) = request.get("command").and_then(Value::as_str) else {
        return error("invalid_request", "command must be a string");
    };
    let thread_id = request
        .get("thread_id")
        .and_then(Value::as_str)
        .unwrap_or(PRIMARY_THREAD);

    let result = match command {
        "status" => json!({
            "service": "codex-bridge-demo",
            "status": "ready",
            "demo": true,
            "protocol_version": 18,
            "rollout_store": {"available": true, "codex_home": "/demo/.codex", "read_only": true},
            "selected_thread_id": PRIMARY_THREAD,
            "write_backend": {"app_server_available": true, "app_server_mode": "demo_wasm", "standalone_fallback": false}
        }),
        "projects" => json!({
            "source": "demo_wasm",
            "include_archived": request.get("include_archived").and_then(Value::as_bool).unwrap_or(false),
            "projects": [{"name": "codex-bridge", "path": PROJECT_PATH, "thread_count": 2, "archived_count": 0, "updated_at_ms": 1_788_767_541_844_u64}]
        }),
        "project_threads" => json!({
            "source": "demo_wasm",
            "project_path": PROJECT_PATH,
            "threads": [state.thread(PRIMARY_THREAD), state.thread(SECONDARY_THREAD)],
            "offset": 0,
            "returned": 2,
            "available": 2
        }),
        "thread_pins" => {
            let thread_ids = state.pinned_thread.iter().collect::<Vec<_>>();
            let threads = thread_ids
                .iter()
                .map(|thread_id| state.thread(thread_id))
                .collect::<Vec<_>>();
            json!({"available": true, "section_id": "demo-pins", "thread_ids": thread_ids, "threads": threads})
        }
        "thread_pin" => {
            let pinned = request
                .get("pinned")
                .and_then(Value::as_bool)
                .unwrap_or(false);
            if pinned {
                state.pinned_thread = Some(thread_id.to_owned());
            } else if state.pinned_thread.as_deref() == Some(thread_id) {
                state.pinned_thread = None;
            }
            json!({"thread_id": thread_id, "pinned": pinned})
        }
        "current" | "select" => {
            json!({"thread": state.thread(thread_id), "selection": {"method": "demo", "authoritative": true}})
        }
        "messages" => {
            let total = state.messages.len();
            let end = request
                .get("before")
                .and_then(Value::as_u64)
                .map(|value| value as usize)
                .unwrap_or(total)
                .min(total);
            let limit = request.get("limit").and_then(Value::as_u64).unwrap_or(30) as usize;
            let start = end.saturating_sub(limit);
            let messages = state.messages[start..end]
                .iter()
                .enumerate()
                .map(|(offset, message)| {
                    let mut message = message.clone();
                    message["message_index"] = json!(start + offset);
                    message
                })
                .collect::<Vec<_>>();
            json!({
                "source": "demo_wasm",
                "tool_source": "demo_wasm",
                "thread": state.thread(thread_id),
                "messages": messages,
                "page": {"start": start, "end": end, "total": total, "has_more": start > 0, "before": start}
            })
        }
        "tool_content" => {
            let message_index = request
                .get("message_index")
                .and_then(Value::as_u64)
                .unwrap_or(0) as usize;
            let tool_index = request
                .get("tool_index")
                .and_then(Value::as_u64)
                .unwrap_or(0) as usize;
            let Some(mut detail) = tool_content(message_index, tool_index) else {
                return error(
                    "tool_content_not_found",
                    "the demo has no detail for this tool",
                );
            };
            detail["thread_id"] = json!(thread_id);
            detail["message_index"] = json!(message_index);
            detail["tool_index"] = json!(tool_index);
            detail
        }
        "thread_watch" => json!({"thread_id": thread_id, "subscribed": true}),
        "pending_messages" => state.pending_messages(),
        "pending_message_delete" => {
            let Some(pending) = state.pending.take() else {
                return error(
                    "pending_message_not_found",
                    "the demo message already handed off",
                );
            };
            json!({"id": pending.id, "thread_id": pending.thread_id, "text": pending.text, "message_action": pending.action, "queue_deleted": true})
        }
        "send" | "steer" => {
            let text = request
                .get("text")
                .and_then(Value::as_str)
                .unwrap_or("")
                .trim();
            if text.is_empty() {
                return error("invalid_request", "message must not be empty");
            }
            if state.pending.is_some() || state.active_ticks > 0 {
                return error(
                    "demo_busy",
                    "Wait for the current simulated response before submitting another message",
                );
            }
            let action = if command == "steer" { "steer" } else { "queue" };
            let id = format!("demo-pending-{}", state.next_pending);
            state.next_pending += 1;
            state.pending = Some(PendingMessage {
                id: id.clone(),
                thread_id: thread_id.to_owned(),
                text: text.to_owned(),
                action: action.to_owned(),
                status: format!("{action}ing"),
                polls: 0,
            });
            json!({"action": command, "status": if command == "steer" { "steered" } else { "queued" }, "pending_id": id, "thread_id": thread_id, "target": "demo_wasm"})
        }
        "thread_activity" => state.activity(thread_id),
        "interrupt" => {
            if state.active_thread.as_deref() != Some(thread_id) || state.active_ticks == 0 {
                return error(
                    "no_active_turn",
                    format!("thread {thread_id} has no active demo turn"),
                );
            }
            state.active_ticks = 0;
            state.active_thread = None;
            state.file_len += 1;
            json!({"thread_id": thread_id, "status": "interrupted", "backend": "demo_wasm"})
        }
        "composer_status" => json!({
            "thread_id": thread_id,
            "model": state.model,
            "reasoning_effort": state.effort,
            "weekly_usage": {"remaining_percent": 63, "resets_at": 1_790_000_000_u64}
        }),
        "composer_options" => models(),
        "thread_settings_update" => {
            state.model = request
                .get("model")
                .and_then(Value::as_str)
                .unwrap_or("gpt-5.6-sol")
                .to_owned();
            state.effort = request
                .get("effort")
                .and_then(Value::as_str)
                .unwrap_or("medium")
                .to_owned();
            json!({"thread_id": thread_id, "model": state.model, "reasoning_effort": state.effort, "backend": "demo_wasm"})
        }
        "thread_rename" => {
            let name = request
                .get("name")
                .and_then(Value::as_str)
                .map(str::trim)
                .unwrap_or("");
            if name.is_empty() || name.chars().count() > 200 {
                return error(
                    "invalid_thread_name",
                    "thread name must contain between 1 and 200 characters",
                );
            }
            state
                .renamed_threads
                .insert(thread_id.to_owned(), name.to_owned());
            state.file_len += 1;
            json!({"thread_id": thread_id, "name": name, "status": "renamed", "backend": "demo_wasm"})
        }
        "workspace_diff" => json!({
            "thread_id": thread_id,
            "repository": PROJECT_PATH,
            "base_branch": "main",
            "base_sha": "da7e084d14eccd6cac359726d802e78ddd1f54de",
            "semantics": "demo_uncommitted_worktree_vs_head",
            "clean": false,
            "files_changed": 4,
            "additions": 214,
            "deletions": 18,
            "untracked_files": 1,
            "untracked_lines_skipped": 0
        }),
        "tail" => {
            json!({"source": "demo_wasm", "messages": state.messages, "messages_total": state.messages.len()})
        }
        "pending" => json!({"requests": []}),
        "scroll" => json!({"status": "simulated", "direction": request.get("direction")}),
        "message_content" => {
            return error(
                "message_content_not_found",
                "the demo messages are already fully loaded",
            )
        }
        "thread_create" | "thread_archive" | "approve" | "decline" | "host_exec"
        | "app_server_rpc" => {
            return error(
                "demo_limited",
                "This operation is intentionally unavailable in the public WASM demo",
            )
        }
        _ => {
            return error(
                "unknown_command",
                format!("unsupported demo command: {command}"),
            )
        }
    };
    success(result)
}

pub fn handle_json(request: &str) -> String {
    let response = match serde_json::from_str::<Value>(request) {
        Ok(request) => STATE.with(|state| dispatch(request, &mut state.borrow_mut())),
        Err(parse_error) => error("invalid_json", parse_error.to_string()),
    };
    serde_json::to_string(&response).expect("demo response serializes")
}

#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub extern "C" fn demo_alloc(len: usize) -> *mut u8 {
    let mut bytes = vec![0_u8; len].into_boxed_slice();
    let pointer = bytes.as_mut_ptr();
    std::mem::forget(bytes);
    pointer
}

#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub unsafe extern "C" fn demo_free(pointer: *mut u8, len: usize) {
    if !pointer.is_null() {
        // SAFETY: the pointer and exact length come from `demo_alloc` or `demo_command`.
        drop(Box::from_raw(std::ptr::slice_from_raw_parts_mut(
            pointer, len,
        )));
    }
}

#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub unsafe extern "C" fn demo_command(pointer: *const u8, len: usize) -> u64 {
    // SAFETY: JavaScript writes `len` initialized bytes into a `demo_alloc` allocation.
    let request = std::slice::from_raw_parts(pointer, len);
    let request = std::str::from_utf8(request).unwrap_or("{}");
    let mut response = handle_json(request).into_bytes().into_boxed_slice();
    let response_len = response.len() as u64;
    let response_pointer = response.as_mut_ptr() as usize as u64;
    std::mem::forget(response);
    (response_len << 32) | (response_pointer & 0xffff_ffff)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn result(response: Value) -> Value {
        assert_eq!(response["ok"], true, "unexpected demo response: {response}");
        response["result"].clone()
    }

    fn land_pending_message(state: &mut DemoState) {
        for _ in 0..3 {
            result(dispatch(json!({"command": "pending_messages"}), state));
        }
    }

    #[test]
    fn status_identifies_the_wasm_demo() {
        let response: Value =
            serde_json::from_str(&handle_json(r#"{"command":"status"}"#)).unwrap();
        assert_eq!(response["result"]["demo"], true);
        assert_eq!(response["result"]["protocol_version"], 18);
    }

    #[test]
    fn messages_have_exact_page_indices() {
        let mut state = DemoState::new();
        let response = dispatch(
            json!({"command": "messages", "thread_id": PRIMARY_THREAD, "limit": 2}),
            &mut state,
        );
        assert_eq!(response["result"]["page"]["start"], 3);
        assert_eq!(response["result"]["page"]["end"], 5);
        assert_eq!(response["result"]["messages"][0]["message_index"], 3);
    }

    #[test]
    fn queued_message_moves_through_buffer_and_into_history() {
        let mut state = DemoState::new();
        let before = state.messages.len();
        let response = result(dispatch(
            json!({"command": "send", "thread_id": PRIMARY_THREAD, "text": "Try the demo"}),
            &mut state,
        ));
        assert_eq!(response["status"], "queued");
        let pending = state.pending_messages();
        assert_eq!(pending["messages"][0]["status"], "queueing");
        assert_eq!(pending["messages"][0]["action"], "queue");
        assert_eq!(state.pending_messages()["messages"][0]["status"], "queued");
        assert!(state.pending_messages()["messages"]
            .as_array()
            .unwrap()
            .is_empty());
        assert_eq!(state.messages.len(), before + 1);
        assert_eq!(state.active_ticks, 3);
    }

    #[test]
    fn polling_refreshes_activity_and_lands_the_demo_reply() {
        let mut state = DemoState::new();
        let initial_messages = state.messages.len();
        let initial_file_len = state.file_len;
        result(dispatch(
            json!({"command": "send", "thread_id": PRIMARY_THREAD, "text": "Refresh me"}),
            &mut state,
        ));
        land_pending_message(&mut state);

        let active = result(dispatch(
            json!({"command": "thread_activity", "thread_id": PRIMARY_THREAD}),
            &mut state,
        ));
        assert_eq!(active["activity"]["active_turn_id"], "demo-turn-processing");
        assert!(active["activity"]["file_len"].as_u64().unwrap() > initial_file_len);

        result(dispatch(
            json!({"command": "thread_activity", "thread_id": PRIMARY_THREAD}),
            &mut state,
        ));
        let completed = result(dispatch(
            json!({"command": "thread_activity", "thread_id": PRIMARY_THREAD}),
            &mut state,
        ));
        assert!(completed["activity"]["active_turn_id"].is_null());

        let messages = result(dispatch(
            json!({"command": "messages", "thread_id": PRIMARY_THREAD, "limit": 30}),
            &mut state,
        ));
        assert_eq!(messages["page"]["total"], initial_messages + 2);
        assert_eq!(
            messages["messages"][initial_messages]["content"][0]["text"],
            "Refresh me"
        );
        assert!(
            messages["messages"][initial_messages + 1]["content"][0]["text"]
                .as_str()
                .unwrap()
                .contains("in-browser WASM demo server")
        );
    }

    #[test]
    fn active_demo_turn_can_be_interrupted_once() {
        let mut state = DemoState::new();
        result(dispatch(
            json!({"command": "send", "thread_id": PRIMARY_THREAD, "text": "Stop me"}),
            &mut state,
        ));
        land_pending_message(&mut state);
        let messages_after_handoff = state.messages.len();
        let file_len_before_interrupt = state.file_len;

        let interrupted = result(dispatch(
            json!({"command": "interrupt", "thread_id": PRIMARY_THREAD}),
            &mut state,
        ));
        assert_eq!(interrupted["status"], "interrupted");
        assert_eq!(state.active_thread, None);
        assert_eq!(state.active_ticks, 0);
        assert_eq!(state.messages.len(), messages_after_handoff);
        assert!(state.file_len > file_len_before_interrupt);

        let inactive = result(dispatch(
            json!({"command": "thread_activity", "thread_id": PRIMARY_THREAD}),
            &mut state,
        ));
        assert!(inactive["activity"]["active_turn_id"].is_null());
        let duplicate = dispatch(
            json!({"command": "interrupt", "thread_id": PRIMARY_THREAD}),
            &mut state,
        );
        assert_eq!(duplicate["ok"], false);
        assert_eq!(duplicate["error"]["code"], "no_active_turn");
    }

    #[test]
    fn demo_exposes_the_frontend_baseline_contract() {
        let mut state = DemoState::new();
        for (request, field) in [
            (json!({"command": "status"}), "service"),
            (json!({"command": "projects"}), "projects"),
            (
                json!({"command": "project_threads", "project_path": PROJECT_PATH}),
                "threads",
            ),
            (json!({"command": "composer_options"}), "models"),
            (
                json!({"command": "workspace_diff", "thread_id": PRIMARY_THREAD}),
                "files_changed",
            ),
        ] {
            assert!(result(dispatch(request, &mut state)).get(field).is_some());
        }
    }

    #[test]
    fn pinning_tracks_the_selected_demo_thread() {
        let mut state = DemoState::new();
        dispatch(
            json!({"command": "thread_pin", "thread_id": SECONDARY_THREAD, "pinned": true}),
            &mut state,
        );
        let pins = dispatch(json!({"command": "thread_pins"}), &mut state);
        assert_eq!(pins["result"]["thread_ids"], json!([SECONDARY_THREAD]));
        assert_eq!(pins["result"]["threads"][0]["id"], SECONDARY_THREAD);
        assert_eq!(state.thread(PRIMARY_THREAD)["pinned"], false);
        assert_eq!(state.thread(SECONDARY_THREAD)["pinned"], true);
    }
}
